kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: dev
  name: admin
subjects:
- kind: ServiceAccount
  name: jane
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io