kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: dev
  name: view
subjects:
- kind: ServiceAccount
  name: ken
roleRef:
  kind: Role
  name: view
  apiGroup: rbac.authorization.k8s.io