image: docker:19.03.11

before_script:
  - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD

stages:
  - build

services:
  - docker:19.03.11-dind

.templates:
  - &build-temp
    script:
      - cd src/${service_name}
      - docker build -t $DOCKER_REGISTRY_USER/${service_name}:$CI_COMMIT_TAG .
      - docker push $DOCKER_REGISTRY_USER/${service_name}:$CI_COMMIT_TAG
    only:
      - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/

adservice:
  stage: build
  <<: *build-temp
  variables:
    service_name: adservice

cartservice:
  stage: build
  <<: *build-temp
  variables:
    service_name: cartservice

checkoutservice:
  stage: build
  <<: *build-temp
  variables:
    service_name: checkoutservice

currencyservice:
  stage: build
  <<: *build-temp
  variables:
    service_name: currencyservice

emailservice:
  stage: build
  <<: *build-temp
  variables:
    service_name: emailservice

frontend:
  stage: build
  <<: *build-temp
  variables:
    service_name: frontend

loadgenerator:
  stage: build
  <<: *build-temp
  variables:
    service_name: loadgenerator

paymentservice:
  stage: build
  <<: *build-temp
  variables:
    service_name: paymentservice

productcatalogservice:
  stage: build
  <<: *build-temp
  variables:
    service_name: productcatalogservice

recommendationservice:
  stage: build
  <<: *build-temp
  variables:
    service_name: recommendationservice

shippingservice:
  stage: build
  <<: *build-temp
  variables:
    service_name: shippingservice
