kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-watch
subjects:
- kind: Group
  name: system:serviceaccounts:prometheus
roleRef:
  kind: ClusterRole
  name: pod-watch
  apiGroup: rbac.authorization.k8s.io