ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    certmanager.k8s.io/acme-challenge-type: http01
  hosts:
    - name: chartmuseum.tennki.tk
      path: /
      tls: true
      tlsSecret: chartmuseum.tennki.tk

env:
  open:
    DISABLE_API: false