apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
     targetPortal: 10.166.0.21
     iqn: iqn.2020-08.gcp.com:dev-storage-iscsi
     lun: 0
     fsType: 'ext4'
     readOnly: false
