repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

  - name: jetstack
    url: https://charts.jetstack.io

  - name: harbor
    url: https://helm.goharbor.io

releases:
  - name: nginx-ingress
    namespace: nginx-ingress
    chart: stable/nginx-ingress
    version: 1.38.0

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 0.9.0
    hooks:
    - events: ["presync"]
      showlogs: true
      command: kubectl
      args: ["apply", "--validate=false", "-f", "https://raw.githubusercontent.com/jetstack/cert-manager/release-0.9/deploy/manifests/00-crds.yaml"]
    - events: ["presync"]
      showlogs: true
      command: kubectl
      args: ["label", "--overwrite", "namespace", "{{`{{.Release.Namespace}}`}}", "certmanager.k8s.io/disable-validation=true"]
    - events: ["postsync"]
      showlogs: true
      command: kubectl
      args: ["apply", "-f", "./charts/cert-manager/clusterissuer.yaml"]

  - name: harbor
    namespace: harbor
    chart: harbor/harbor
    version: 1.1.2
    values:
      - ./values/harbor.yaml